
spring:
  profiles:
    active: security
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:client-secret}
          google:
            client-id: ${GOOGLE_CLIENT_ID:client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:client-secret}
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb

progi:
  fronted:
    url: ${FRONTEND_URL:http://localhost:5173}
