
spring:
  profiles:
    active: security
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:client-secret}
          google:
            client-id: ${GOOGLE_CLIENT_ID:client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:client-secret}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        http-only: true

progi:
  fronted:
    url: ${FRONTEND_URL:http://localhost:5173}
